version: "2.1"
services:
  db:
    build: Database/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d database"]
      interval: 5s
      timeout: 5s
      retries: 5
  datalake:
    build: Dataload/
    depends_on:
      db:
        condition: service_healthy

