
CREATE SCHEMA DATALAKE;
CREATE SCHEMA TRANSACTIONS;

CREATE TABLE DATALAKE.TRANSACTION_RAW_DATA (
    ID SERIAL PRIMARY KEY,
    TRANSACTION_DATA jsonb,
    ETL_LOAD_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE  TRANSACTIONS.DIM_CUSTOMER (
CUSTOMER_ID SERIAL PRIMARY KEY,
CUSTOMER_FIRST_NAME VARCHAR ,
CUSTOMER_LAST_NAME VARCHAR,
CUSTOMER_SSN VARCHAR,
ETL_LOAD_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE  TRANSACTIONS.DIM_TRANSACTION_TYPE (
TRANSACTION_TYPE_ID SERIAL PRIMARY KEY,
TRANSACTION_TYPE_NAME VARCHAR ,
ETL_LOAD_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE TRANSACTIONS.FACT_TRANSACTION (
    TRANSACTION_ID VARCHAR,
    SUB_TRANSACTION_ID int,
    TRANSACTION_DATE DATE,
    TRANSACTION_TYPE INT ,
    CUSTOMER_ID     INT,
    TERMS VARCHAR,
    TOTAL_AMOUNT NUMERIC(30,10),
    ETL_LOAD_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE TRANSACTIONS.FACT_TRANSACTION_LINE_ITEMS (
    TRANSACTION_ID varchar,
    SUB_TRANSACTION_ID int,
    TRANSACTION_LINE_ITEM_ID int,
    PRODUCT_NAME varchar ,
    UNIT_NAME varchar,
    TOTAL_QUANTITY int,
    ETL_LOAD_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);